### ISSUE TITLE
Does « bufferevent_base_connect() » actually exists ?

### ISSUE THREAD

**Issue by Gingerbreadz** [libevent/libevent-book#32]
Hey,

This `bufferevent_base_connect()` function is mentionned in the book around here https://github.com/nmathewson/libevent-book/blob/9e9e5242f6fcd4cc6bfe564c22756ab6f5ce5914/Ref6_bufferevent.txt#L296
I can not find any other occurence of it in the book or in the libevent api.
Should I be reading `bufferevent_socket_connect()` instead ?

**Comment by nmathewson** [comment]
Yes, I think that bufferevent_socket_connect() is the right name.  Do you have time to make a pull request for this?
