### ISSUE TITLE
Why named asynchronous IO?

### ISSUE THREAD

**Issue by liuyunbin** [libevent/libevent-book#35]
In

https://github.com/nmathewson/libevent-book/blob/ab4dd1107bbfe419e94ccabbe9473b542173bccd/01_intro.txt#L5

why named  asynchronous IO?

In my opinion,  `asynchronous IO` is use like  `aio_write, aio_read` , but libevent use like `epoll` , so there should use `synchronous nonblocking IO`

**Comment by azat** [comment]
That is correct, thank you for the report! Fixed.
