### ISSUE TITLE
FD_SET(i, &readset)?

### ISSUE THREAD

**Issue by ghost** [libevent/libevent-book#8]
In file "01intro.txt"

   /\* Add all of the interesting fds to readset */
    for (i=0; i < n_sockets; ++i) {
         if (fd[i]>maxfd) maxfd = fd[i];
         FD_SET(i, &readset);
    }

Should it be FD_SET(fd[i], &readset)? I'm not sure about it.

**Comment by azat** [comment]
Fixed in 96fd5b6584568cd6e6ee24fa
